# ArgoCD Application for the Istio Standalone Operator

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: manifests/charts/istio-operator
    repoURL: https://github.com/istio/istio
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      selfHeal: true
      prune: true