argo-cd:
  dex:
    enabled: false
  
  server:
    config:
      # Enables application status badge feature
      statusbadge.enabled: 'true'

applications:
  istio-operator:
    enabled: true
    repository: https://github.com/istio/istio
    revision: HEAD
    path: manifests/charts/istio-operator
    namespace: istio-operator
    prune: true
    selfHeal: true
